use inventorymanagementdb;

-- 1. Display all products.
select * from products;

-- 2. Display all customers.
select * from customers;

-- 3. Find products above price 100.
select productname, unitprice from products where unitprice > 100;

-- 4. List suppliers from Chicago.
select * from suppliers where city = 'chicago';

-- 5. Display customers ordered by name.
select customername from customers order by customername asc;

-- 6. Count customers.
select count(customerid) as Number_of_Customers from customers;

-- 7. Count suppliers.
select count(*) as Number_of_Suppliers from suppliers;

-- 8. Show products by category.
select  ca.categoryname, count(p.productname) as Number_of_products from categories ca inner join subcategories sb on ca.categoryid = sb.categoryid inner join products p on sb.subcategoryid = p.subcategoryid group by ca.categoryname;

-- 9. Find Average, Lowest and Highest product price.
select avg(unitprice), min(unitprice), max(unitprice) from products;

-- 10. Top 5 Suppliers based on Total Purchase Value. 
select sp.suppliername, po.totalamount from suppliers sp join purchaseorders po on sp.supplierid = po.supplierid order by po.totalamount desc limit 5;

-- 11. Show Revenue (total amount) generated by Customer Type.
select cu.customertype, sum(so.totalamount) from customers cu join salesorders so on cu.customerid = so.customerid group by cu.customertype;

-- 12. Count orders.
select count(purchaseorderid) from purchaseorders;

-- 13. Show bottom 10 customers who generated lowest revenue (total amount)
select cu.customerid, cu.customername from customers cu join salesorders so on cu.customerid= so.customerid order by so.totalamount asc limit 10; 

-- 14. Find products with reorder level below 10.
select productid, productname, reorderlevel from products where reorderlevel < 10 order by productid asc;

-- 15. How many sales orders are currently 'Pending', 'Shipped', or 'Cancelled'?
SELECT OrderStatus, COUNT(SalesOrderID) AS TotalOrders FROM SalesOrders WHERE OrderStatus IN ('Pending', 'Shipped', 'Cancelled') GROUP BY OrderStatus;

-- 16. Customers from South James.
select customername, city from customers where city= "South James";

-- 17. Products ordered alphabetically.
select * from products order by  productname asc; 

-- 19. Total sales orders.
select sum(salesorderid) from salesorders;

-- 20. Product sales summary.
select p.productname, sum(soi.quantity) from products p join salesorderitems soi on p.productid= soi.productid group by productname;

-- 21. List the ProductName, SKU, and UnitPrice for all products that cost more than the average unit price of all products.
select productname, sku, unitprice from products where unitprice > (select avg(unitprice) from products) order by unitprice desc ;

-- 22. Find the names of all Warehouses that have never had any transactions recorded in the InventoryTransactions table. 
select warehousename from warehouses where warehouseid not in ( select warehouseid from inventorytransactions where warehouseid is not null);

-- 23. Find all Products that have never been ordered by a customer.
select productid, productname from products where productid not in (select productid from salesorderitems where productid is not null);

-- 24. List the CustomerName and Phone of all customers who have placed at least one sales order.
select customername, phone from customers where customerid in ( select distinct customerid from salesorders);

-- 25. Find the names of all Suppliers who have at least one pending purchase order. 
select suppliername from suppliers where supplierid in (select distinct supplierid from purchaseorders where orderstatus= 'pending');

-- 26. Find the details of all SalesOrders that have a TotalAmount greater than the highest single payment ever made in the Payments table.
select * from salesorders where totalamount > (select max(amount) from payments);  

-- 27. List all ProductName and SKU items that belong to the 'category_7' category.
select productname, sku from products where subcategoryid in ( select subcategoryid from subcategories where categoryid in (select categoryid from categories where categoryname= 'category_7'));

-- 28. Rank products within each subcategory based on their total sales quantity. Show the top 3 highest-selling products for every single subcategory. 
with RankedProducts as (select p.productid, p.subcategoryid, p.productname, sum(soi.quantity) as totalsalesquantity, dense_rank() over(partition by p.subcategoryid order by SUM(soi.quantity) desc) as salesrank from products p join salesorderitems soi on p.productid= soi.productid group by p.productid, p.subcategoryid, p.productname) select productid, subcategoryid, productname, totalsalesquantity, salesrank from rankedproducts where salesrank <= 3 order by salesrank, subcategoryid;

-- 29. For each CustomerType, rank customers based on their lifetime TotalAmount spent.
with rankedproducts as (select cu.customerid, cu.customertype, sum(so.totalamount) as lifetimetotalamountspent, dense_rank() over (partition by cu.customertype order by sum(so.totalamount) desc) as customerrank from customers cu join salesorders so on cu.customerid=so.customerid group by cu.customerid, cu.customertype) select customerid, customertype, lifetimetotalamountspent, customerrank from rankedproducts;

-- 30. For each customer, list their orders alongside the date of their previous order and calculate the number of days that passed between the two orders. (Hint: Use the LAG() function).
with orderintervals as (select customerid, salesorderid, orderdate, lag(orderdate, 1) over (partition by customerid order by orderdate asc, salesorderid asc) as previousorderdate from salesorders) SELECT oi.CustomerID, cu.CustomerName, oi.SalesOrderID, oi.OrderDate, oi.PreviousOrderDate FROM OrderIntervals oi JOIN Customers cu ON oi.CustomerID = cu.CustomerID ORDER BY oi.CustomerID ASC, oi.OrderDate ASC; 

-- 31. Write a query using a CTE to calculate the total item count and total line amount for each order line in SalesOrderItems. In your main query, filter the result to only show order lines where the total calculated line amount is greater than $1,000.
with calculatedorderlines as (select salesitemid, salesorderid, productid, quantity, unitprice, (quantity * unitprice) as calculatedlineamount from salesorderitems) select salesitemid, salesorderid, productid, quantity, unitprice, calculatedlineamount from calculatedorderlines where calculatedlineamount > 10000 order by calculatedlineamount desc;

-- 32. Create a CTE that joins SalesOrders with Customers to create a flat list of SalesOrderID, OrderDate, TotalAmount, and CustomerName. In the main query, select from this CTE to find all orders placed in the current year.
with orderprofiles as (select so.salesorderid, so.orderdate, so.totalamount, cu.customername from salesorders so join customers cu on cu.customerid= so.customerid) select salesorderid, orderdate, totalamount, customername from orderprofiles where extract(year from orderdate) = 2026 order by orderdate asc;

-- 33. Use a CTE to pull a simple list of SubCategoryID, SubCategoryName, and its parent CategoryName (by joining those two tables). In your main query, select from this CTE to list all subcategories that belong to the 'categoty_3' category.
with subcategorieslist as (select sb.subcategoryid, sb.subcategoryname, ca.categoryname from subcategories sb join categories ca on sb.categoryid= ca.categoryid) select subcategoryid, subcategoryname from subcategorieslist where categoryname= 'category_3' order by subcategoryname asc;

-- 34. Create a CTE that pulls a unique list of all ProductIDs present in the InventoryTransactions table. In your outer query, select all product names from the Products table whose ID is found in that CTE.
with uniqueproductid as (select distinct productid from inventorytransactions) select p.productid, p.productname, p.sku from products p join uniqueproductid up on up.productid= p.productid order by p.productname asc; 

-- 35. Create a CTE called ActiveSuppliers that filters the Suppliers table for only chicago city with a status of 'Active'. In your main query, pull from this CTE to extract a mailing list showing just the SupplierName, ContactPerson, and Email.
with activesuppliers as (select suppliername from suppliers where city='chicago' and status ='active') select s.suppliername, s.contactperson, s.email from suppliers s join activesuppliers ac on s.suppliername = ac.suppliername order by s.suppliername asc;

-- 36.  Write a query to create a view named v_ProductCatalog that combines the products, subcategories, and categories tables. This view should display the product ID, name, SKU, unit price, subcategory name, and main category name for easy searching.
create view v_productcatalog as select p.productid, p.productname, p.sku, p.unitprice, c.categoryname, sb.subcategoryname  from products p join subcategories sb on sb.subcategoryid = p.subcategoryid join categories c on c.categoryid = sb.categoryid;

select * from v_productcatalog;


-- 37. Create a view called v_SalesOrderSummary that joins sales orders, customers, and payments to show an overview of every order. It needs to display the order ID, customer name, order status, total amount, and the total amount paid so far.
create view v_salesordersummary as select so.salesorderid, cu.customername, so.orderstatus, so.totalamount, p.amount from customers cu join salesorders so on cu.customerid= so.customerid join payments p on so.salesorderid = p.salesorderid;

select * from v_salesordersummary;


-- 38. Write a trigger named trgSetCreatedDate that fires automatically before a new user is inserted into the Users table. The trigger should set the CreatedDate field to the current system date and time if it is left blank.
DELIMITER //
Create trigger trgSetCreatedDate
before insert on Users
for each row
begin
if new.createdDate is null then
        set new.createdDate = NOW();
    end if;
end //

DELIMITER ;

select * from users;
set foreign_key_checks = 0;
insert into users values (51, 4, 'Pradeep Kumar', 'pradeep39@example.org', 878798678, null);
set foreign_key_checks = 1;
select * from users;



-- 39. Write a query that selects SupplierName and uses a CASE statement to create a new column called AccountStatus.If Status is 'Active' (or 1), show "Fully Approved".If Status is 'Inactive' (or 0), show "On Hold".For any other value, show "Under Review".
Select SupplierName, Status,
case 
when status = 'Active' then 'Fully Approved'
when status = 'Inactive' then 'On Hold'
else 'Under Review'
end as AccountStatus from Suppliers;

-- 40.  Write a query for the Customers table that outputs CustomerName alongside a column named ContactCompleteness.If both Email AND Phone are missing (IS NULL), label them as "No Contact Info".If only one is missing, label them as "Partial Info".If both are present, label them as "Complete Profile".
select customername, email, phone, case when email = 'null' and phone ='null' then 'No contact info' when email='null' or phone ='null' then 'partial info' else 'complete profile' end as contactcompleteness from customers;

-- 41. Write a query on the PurchaseOrders table that selects PurchaseOrderID and OrderStatus. Add a calculated column named RequiresFollowUp.If OrderStatus is 'Pending', display 'Yes'.If it is anything else, display 'No'. 
select purchaseorderid, orderstatus, if (orderstatus= 'pending', 'Yes', 'No') as Requiredfollowup from purchaseorders;

-- 42. Query the Products table to list ProductName and UnitPrice. Create a new column named PriceTier.If UnitPrice is greater than 500, label it 'Premium'. If it is less than or equal to ₹1,00, label it 'Standard'.
select productname, unitprice, if (unitprice > 500, 'Premium', 'Standard') as PriceTier from products;

-- 43. Write a query on the SalesOrders table displaying SalesOrderID and TotalAmount. Add an audit column called InsuranceRequired.If TotalAmount is greater than ₹5000, return the number 1 (or 'Required').Otherwise, return the number 0 (or 'Not Required').
select salesorderid, totalamount, if (totalamount > 5000, 1, 0) as InsuranceRequired from salesorders;
